// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB-pT3cE31StvMndHYqiYzyeKicCNqT8k',
    appId: '1:170873898477:web:578a9b7654de4f5b21d3e4',
    messagingSenderId: '170873898477',
    projectId: 'luminaraug',
    authDomain: 'luminaraug.firebaseapp.com',
    storageBucket: 'luminaraug.firebasestorage.app',
    measurementId: 'G-4G4EE24H3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgvoiBoQ3LU14B8ps3NmGtTGiMV--fT_M',
    appId: '1:170873898477:android:a7168a0ce94c129b21d3e4',
    messagingSenderId: '170873898477',
    projectId: 'luminaraug',
    storageBucket: 'luminaraug.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_887b7JLLCED49mnDEQPR88IVETc6H84',
    appId: '1:170873898477:ios:da8099ea9cdf048121d3e4',
    messagingSenderId: '170873898477',
    projectId: 'luminaraug',
    storageBucket: 'luminaraug.firebasestorage.app',
    iosBundleId: 'com.example.fbgoogle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB-pT3cE31StvMndHYqiYzyeKicCNqT8k',
    appId: '1:170873898477:web:e5ac38b4d704a54621d3e4',
    messagingSenderId: '170873898477',
    projectId: 'luminaraug',
    authDomain: 'luminaraug.firebaseapp.com',
    storageBucket: 'luminaraug.firebasestorage.app',
    measurementId: 'G-B995LCKYCE',
  );
}
